--- 
- name: install neutron packages
  yum: name="{{ packages }}" state=latest
  vars:
    packages:
    - openstack-neutron-openvswitch
    - ebtables
    - ipset

- name: create neutron server configuration file
  template: src=neutron.conf.j2 dest=/etc/neutron/neutron.conf

- name: create neutron openvswitch plugin configuration file
  template: src=openvswitch_agent.ini.j2 dest=/etc/neutron/plugins/ml2/openvswitch_agent.ini

- name: start openstack-nova-compute service
  service: name=openstack-nova-compute state=restarted enabled=yes

- name: start neutron-openvswitch-agent service
  service: name=neutron-openvswitch-agent state=restarted enabled=yes
